# Generated by Django 4.0.4 on 2022-05-31 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('font_color', models.CharField(choices=[('#FFFFFF', 'White'), ('#000000', 'Black')], default='#FFFFFF', max_length=7)),
                ('background_color', models.CharField(max_length=7)),
                ('border_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=400)),
                ('icon', models.CharField(max_length=12)),
                ('link', models.URLField()),
                ('color', models.CharField(max_length=7)),
                ('tags', models.ManyToManyField(blank=True, to='projects.tag')),
            ],
        ),
    ]
