# Generated by Django 4.0.4 on 2022-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='tic-tac-toe', max_length=40),
            preserve_default=False,
        ),
    ]
